function [W] = W_matrix(q,dq,ddq)

com_upper_leg = 0.5;
com_lower_leg = 0.5;
mass_upper_leg = 1;
mass_lower_leg = 1;
l_upper_leg = 1;
l_lower_leg = 1;
g=9.8;

  W(1,1)=com_upper_leg^2*ddq(1)*mass_upper_leg + ddq(1)*l_upper_leg^2*mass_lower_leg +...
          com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(2))^2 + com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(4))^2 +...
          com_upper_leg^2*ddq(3)*mass_upper_leg*sin(q(2)) + ddq(3)*l_upper_leg^2*mass_lower_leg*sin(q(2)) + com_lower_leg^2*...
         ddq(3)*mass_lower_leg*cos(q(4))^2*sin(q(2)) + 2*com_upper_leg^2*dq(3)*dq(2)*mass_upper_leg*cos(q(2)) + 2*...
         dq(3)*dq(2)*l_upper_leg^2*mass_lower_leg*cos(q(2)) - com_upper_leg^2*ddq(1)*mass_upper_leg*cos(q(3))^2*...
         cos(q(2))^2 - com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(2))^2*cos(q(4))^2 - ddq(1)*l_upper_leg^2*...
         mass_lower_leg*cos(q(3))^2*cos(q(2))^2 - com_lower_leg^2*dq(2)*dq(1)*mass_lower_leg*sin(2*q(2)) - com_lower_leg^2*...
         dq(1)*dq(4)*mass_lower_leg*sin(2*q(4)) + com_lower_leg^2*ddq(4)*mass_lower_leg*cos(q(2))*sin(q(3)) + 2*...
         com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*cos(q(4)) + 2*com_lower_leg^2*dq(3)*dq(4)*mass_lower_leg*...
         cos(q(3))*cos(q(2)) - 2*com_lower_leg*dq(1)*dq(4)*l_upper_leg*mass_lower_leg*sin(q(4)) - 2*com_upper_leg^2*...
         dq(3)*dq(2)*mass_upper_leg*cos(q(3))^2*cos(q(2)) + 2*com_lower_leg^2*dq(3)*dq(2)*mass_lower_leg*cos(q(2))*...
         cos(q(4))^2 - 2*dq(3)*dq(2)*l_upper_leg^2*mass_lower_leg*cos(q(3))^2*cos(q(2)) - com_upper_leg^2*ddq(2)*...
         mass_upper_leg*cos(q(3))*cos(q(2))*sin(q(3)) - ddq(2)*l_upper_leg^2*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(3)) -...
          com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(3))^2*cos(q(2))^2*cos(q(4))^2 + 2*com_lower_leg*ddq(3)*l_upper_leg*...
         mass_lower_leg*cos(q(4))*sin(q(2)) + com_upper_leg^2*dq(2)^2*mass_upper_leg*cos(q(3))*sin(q(3))*sin(q(2)) +...
          dq(2)^2*l_upper_leg^2*mass_lower_leg*cos(q(3))*sin(q(3))*sin(q(2)) + 4*com_lower_leg*dq(3)*dq(2)*...
         l_upper_leg*mass_lower_leg*cos(q(2))*cos(q(4)) + 2*com_lower_leg*dq(2)*dq(1)*l_upper_leg*mass_lower_leg*...
         cos(q(3))*sin(q(4)) + com_lower_leg^2*dq(2)^2*mass_lower_leg*cos(q(3))*cos(q(4))^2*sin(q(3))*sin(q(2)) - 2*...
         com_lower_leg*dq(3)*dq(4)*l_upper_leg*mass_lower_leg*sin(q(2))*sin(q(4)) - 2*com_lower_leg^2*dq(3)*dq(4)*...
         mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))^2 - 2*com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*cos(q(3))^2*...
         cos(q(2))^2*cos(q(4)) + 2*com_upper_leg^2*dq(3)*dq(1)*mass_upper_leg*cos(q(3))*cos(q(2))^2*sin(q(3)) + 2*...
         com_upper_leg^2*dq(2)*dq(1)*mass_upper_leg*cos(q(3))^2*cos(q(2))*sin(q(2)) + 2*com_lower_leg^2*dq(2)*dq(1)*...
         mass_lower_leg*cos(q(2))*cos(q(4))^2*sin(q(2)) + 2*com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*cos(q(2))^2*...
         cos(q(4))*sin(q(4)) + 2*dq(3)*dq(1)*l_upper_leg^2*mass_lower_leg*cos(q(3))*cos(q(2))^2*sin(q(3)) + 2*dq(2)*...
         dq(1)*l_upper_leg^2*mass_lower_leg*cos(q(3))^2*cos(q(2))*sin(q(2)) - 2*com_lower_leg^2*dq(2)*dq(4)*...
         mass_lower_leg*cos(q(4))^2*sin(q(3))*sin(q(2)) - com_lower_leg^2*ddq(3)*mass_lower_leg*cos(q(3))*cos(q(2))*...
         cos(q(4))*sin(q(4)) - com_lower_leg^2*ddq(2)*mass_lower_leg*cos(q(4))*sin(q(3))*sin(q(2))*sin(q(4)) -...
          com_lower_leg*ddq(3)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(4)) + com_lower_leg*ddq(4)*l_upper_leg*...
         mass_lower_leg*cos(q(2))*cos(q(4))*sin(q(3)) - 2*com_lower_leg^2*dq(3)*dq(2)*mass_lower_leg*cos(q(3))^2*cos(q(2))*...
         cos(q(4))^2 - com_lower_leg*ddq(2)*l_upper_leg*mass_lower_leg*sin(q(3))*sin(q(2))*sin(q(4)) - com_lower_leg^2*...
         ddq(2)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))^2*sin(q(3)) + com_lower_leg^2*dq(3)^2*mass_lower_leg*...
         cos(q(2))*cos(q(4))*sin(q(3))*sin(q(4)) - com_lower_leg^2*dq(2)^2*mass_lower_leg*cos(q(2))*cos(q(4))*...
         sin(q(3))*sin(q(4)) + 2*com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(2)) + 2*...
         com_lower_leg^2*dq(2)*dq(1)*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(4)) - 2*com_lower_leg^2*dq(3)*dq(4)*...
         mass_lower_leg*cos(q(4))*sin(q(2))*sin(q(4)) + com_lower_leg*dq(3)^2*l_upper_leg*mass_lower_leg*cos(q(2))*...
         sin(q(3))*sin(q(4)) - com_lower_leg*dq(2)^2*l_upper_leg*mass_lower_leg*cos(q(2))*sin(q(3))*sin(q(4)) -...
          com_lower_leg*dq(4)^2*l_upper_leg*mass_lower_leg*cos(q(2))*sin(q(3))*sin(q(4)) - 2*com_lower_leg*dq(2)*dq(4)*...
         l_upper_leg*mass_lower_leg*cos(q(4))*sin(q(3))*sin(q(2)) - 4*com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*...
         cos(q(3))*cos(q(2))*cos(q(4))^2*sin(q(2)) - 4*com_lower_leg^2*dq(2)*dq(1)*mass_lower_leg*cos(q(3))*...
         cos(q(2))^2*cos(q(4))*sin(q(4)) - 2*com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))*...
         sin(q(2))*sin(q(4)) - 4*com_lower_leg*dq(3)*dq(2)*l_upper_leg*mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4)) -...
          4*com_lower_leg*dq(2)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))^2*sin(q(4)) - 2*...
         com_lower_leg*ddq(2)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))*sin(q(3)) - 2*com_lower_leg*ddq(1)*...
         l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(2))*sin(q(4)) + 2*com_lower_leg^2*dq(3)*dq(1)*...
         mass_lower_leg*cos(q(3))*cos(q(2))^2*cos(q(4))^2*sin(q(3)) + 2*com_lower_leg^2*dq(2)*dq(1)*mass_lower_leg*...
         cos(q(3))^2*cos(q(2))*cos(q(4))^2*sin(q(2)) + 2*com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*cos(q(3))^2*...
         cos(q(2))^2*cos(q(4))*sin(q(4)) + 2*com_lower_leg*dq(1)*dq(4)*l_upper_leg*mass_lower_leg*cos(q(3))^2*...
         cos(q(2))^2*sin(q(4)) + 2*com_lower_leg*dq(2)^2*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(3))*...
         sin(q(2)) + 4*com_lower_leg*dq(3)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))^2*cos(q(4))*sin(q(3)) +...
          4*com_lower_leg*dq(2)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4))*sin(q(2)) + 2*...
         com_lower_leg^2*dq(2)*dq(4)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))*sin(q(3))*sin(q(4)) + 2*com_lower_leg^2*...
         dq(3)*dq(1)*mass_lower_leg*cos(q(2))*cos(q(4))*sin(q(3))*sin(q(2))*sin(q(4)) - 2*com_lower_leg*dq(1)*...
         dq(4)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))*sin(q(2)) + 2*com_lower_leg*dq(2)*dq(4)*...
         l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(3))*sin(q(4)) + 2*com_lower_leg*dq(3)*dq(1)*l_upper_leg*...
         mass_lower_leg*cos(q(2))*sin(q(3))*sin(q(2))*sin(q(4));
  W(2,1)=com_lower_leg^2*ddq(2)*mass_lower_leg + com_upper_leg^2*ddq(2)*mass_upper_leg*cos(q(3))^2 -...
          com_lower_leg^2*ddq(2)*mass_lower_leg*cos(q(4))^2 + ddq(2)*l_upper_leg^2*mass_lower_leg*cos(q(3))^2 +...
          (com_lower_leg^2*dq(1)^2*mass_lower_leg*sin(2*q(2)))/2 - com_lower_leg^2*ddq(4)*mass_lower_leg*cos(q(3)) + 2*...
         com_lower_leg^2*dq(3)*dq(4)*mass_lower_leg*sin(q(3)) - com_upper_leg*g*mass_upper_leg*cos(q(3))*sin(q(2)) +...
          com_lower_leg*g*mass_lower_leg*cos(q(2))*sin(q(4)) - g*l_upper_leg*mass_lower_leg*cos(q(3))*sin(q(2)) +...
          com_lower_leg^2*ddq(2)*mass_lower_leg*cos(q(3))^2*cos(q(4))^2 - com_upper_leg^2*dq(3)*dq(2)*mass_upper_leg*sin(2*...
         q(3)) + com_lower_leg^2*dq(2)*dq(4)*mass_lower_leg*sin(2*q(4)) - dq(3)*dq(2)*l_upper_leg^2*mass_lower_leg*...
         sin(2*q(3)) + 2*com_lower_leg*ddq(2)*l_upper_leg*mass_lower_leg*cos(q(3))^2*cos(q(4)) - com_lower_leg*...
         dq(3)^2*l_upper_leg*mass_lower_leg*cos(q(3))*sin(q(4)) - com_lower_leg*dq(1)^2*l_upper_leg*mass_lower_leg*...
         cos(q(3))*sin(q(4)) + com_lower_leg*dq(4)^2*l_upper_leg*mass_lower_leg*cos(q(3))*sin(q(4)) + 2*...
         com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*sin(q(3))*sin(q(2)) - com_lower_leg*g*mass_lower_leg*cos(q(3))*cos(q(4))*...
         sin(q(2)) - com_upper_leg^2*dq(1)^2*mass_upper_leg*cos(q(3))^2*cos(q(2))*sin(q(2)) - com_lower_leg^2*dq(1)^2*...
         mass_lower_leg*cos(q(2))*cos(q(4))^2*sin(q(2)) - dq(1)^2*l_upper_leg^2*mass_lower_leg*cos(q(3))^2*cos(q(2))*...
         sin(q(2)) - 2*com_upper_leg^2*dq(3)*dq(1)*mass_upper_leg*cos(q(3))^2*cos(q(2)) - 2*dq(3)*dq(1)*l_upper_leg^2*...
         mass_lower_leg*cos(q(3))^2*cos(q(2)) - 2*com_lower_leg^2*dq(3)*dq(4)*mass_lower_leg*cos(q(4))^2*sin(q(3)) -...
          com_upper_leg^2*ddq(1)*mass_upper_leg*cos(q(3))*cos(q(2))*sin(q(3)) - ddq(1)*l_upper_leg^2*mass_lower_leg*cos(q(3))*...
         cos(q(2))*sin(q(3)) - com_lower_leg^2*ddq(3)*mass_lower_leg*cos(q(4))*sin(q(3))*sin(q(4)) - com_lower_leg*...
         ddq(4)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(4)) - com_lower_leg*ddq(3)*l_upper_leg*mass_lower_leg*...
         sin(q(3))*sin(q(4)) - com_lower_leg^2*dq(3)^2*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(4)) - com_lower_leg^2*...
         dq(1)^2*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(4)) + 2*com_lower_leg^2*dq(1)^2*mass_lower_leg*cos(q(3))*...
         cos(q(2))^2*cos(q(4))*sin(q(4)) - 2*com_lower_leg^2*dq(3)*dq(2)*mass_lower_leg*cos(q(3))*cos(q(4))^2*sin(q(3)) -...
          2*com_lower_leg^2*dq(2)*dq(4)*mass_lower_leg*cos(q(3))^2*cos(q(4))*sin(q(4)) + 2*com_lower_leg*...
         dq(1)^2*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))^2*sin(q(4)) - 2*com_lower_leg^2*dq(1)*dq(4)*...
         mass_lower_leg*cos(q(4))^2*sin(q(3))*sin(q(2)) - com_lower_leg^2*dq(1)^2*mass_lower_leg*cos(q(3))^2*cos(q(2))*...
         cos(q(4))^2*sin(q(2)) - com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(4))*sin(q(3))*sin(q(2))*sin(q(4)) - 2*...
         com_lower_leg*dq(2)*dq(4)*l_upper_leg*mass_lower_leg*cos(q(3))^2*sin(q(4)) - 2*com_lower_leg^2*dq(3)*dq(1)*...
         mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4))^2 - com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*sin(q(3))*...
         sin(q(2))*sin(q(4)) - com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))^2*sin(q(3)) - 2*...
         com_lower_leg*dq(3)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*sin(q(2))*sin(q(4)) - 2*com_lower_leg*dq(1)^2*...
         l_upper_leg*mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4))*sin(q(2)) - 4*com_lower_leg*dq(3)*dq(1)*l_upper_leg*...
         mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4)) - 2*com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*...
         cos(q(2))*cos(q(4))*sin(q(3)) - 2*com_lower_leg^2*dq(3)*dq(1)*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(2))*...
         sin(q(4)) - 4*com_lower_leg*dq(3)*dq(2)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(3)) + 2*...
         com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))*sin(q(3))*sin(q(4)) + 2*com_lower_leg*...
         dq(1)*dq(4)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(3))*sin(q(4));
  W(3,1)=com_upper_leg^2*ddq(3)*mass_upper_leg + ddq(3)*l_upper_leg^2*mass_lower_leg +...
          com_lower_leg^2*ddq(3)*mass_lower_leg*cos(q(4))^2 + (com_upper_leg^2*dq(2)^2*mass_upper_leg*sin(2*q(3)))/2 +...
          (dq(2)^2*l_upper_leg^2*mass_lower_leg*sin(2*q(3)))/2 + com_upper_leg^2*ddq(1)*mass_upper_leg*sin(q(2)) +...
          ddq(1)*l_upper_leg^2*mass_lower_leg*sin(q(2)) + com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(4))^2*...
         sin(q(2)) - com_upper_leg*g*mass_upper_leg*cos(q(2))*sin(q(3)) - g*l_upper_leg*mass_lower_leg*cos(q(2))*...
         sin(q(3)) - com_lower_leg^2*dq(3)*dq(4)*mass_lower_leg*sin(2*q(4)) + 2*com_lower_leg*ddq(3)*l_upper_leg*...
         mass_lower_leg*cos(q(4)) - com_lower_leg*g*mass_lower_leg*cos(q(2))*cos(q(4))*sin(q(3)) - com_upper_leg^2*dq(1)^2*...
         mass_upper_leg*cos(q(3))*cos(q(2))^2*sin(q(3)) + com_lower_leg^2*dq(2)^2*mass_lower_leg*cos(q(3))*cos(q(4))^2*...
         sin(q(3)) - 2*com_lower_leg*dq(3)*dq(4)*l_upper_leg*mass_lower_leg*sin(q(4)) - dq(1)^2*l_upper_leg^2*...
         mass_lower_leg*cos(q(3))*cos(q(2))^2*sin(q(3)) + 2*com_upper_leg^2*dq(2)*dq(1)*mass_upper_leg*cos(q(3))^2*...
         cos(q(2)) + 2*dq(2)*dq(1)*l_upper_leg^2*mass_lower_leg*cos(q(3))^2*cos(q(2)) - 2*com_lower_leg^2*dq(2)*dq(4)*...
         mass_lower_leg*cos(q(4))^2*sin(q(3)) - com_lower_leg^2*ddq(2)*mass_lower_leg*cos(q(4))*sin(q(3))*sin(q(4)) + 2*...
         com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*cos(q(4))*sin(q(2)) - com_lower_leg*ddq(2)*l_upper_leg*...
         mass_lower_leg*sin(q(3))*sin(q(4)) - 2*com_lower_leg*dq(2)*dq(4)*l_upper_leg*mass_lower_leg*cos(q(4))*sin(q(3)) -...
          2*com_lower_leg*dq(1)*dq(4)*l_upper_leg*mass_lower_leg*sin(q(2))*sin(q(4)) - 2*com_lower_leg^2*dq(1)*...
         dq(4)*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4))^2 - com_lower_leg^2*ddq(1)*mass_lower_leg*cos(q(3))*...
         cos(q(2))*cos(q(4))*sin(q(4)) - com_lower_leg^2*dq(1)^2*mass_lower_leg*cos(q(3))*cos(q(2))^2*cos(q(4))^2*...
         sin(q(3)) - com_lower_leg*ddq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*sin(q(4)) + 2*com_lower_leg^2*...
         dq(2)*dq(1)*mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4))^2 + 2*com_lower_leg*dq(2)^2*l_upper_leg*...
         mass_lower_leg*cos(q(3))*cos(q(4))*sin(q(3)) - 2*com_lower_leg^2*dq(1)*dq(4)*mass_lower_leg*cos(q(4))*sin(q(2))*...
         sin(q(4)) + 2*com_lower_leg*dq(2)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))*sin(q(2))*sin(q(4)) - 2*...
         com_lower_leg*dq(1)^2*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))^2*cos(q(4))*sin(q(3)) + 4*com_lower_leg*...
         dq(2)*dq(1)*l_upper_leg*mass_lower_leg*cos(q(3))^2*cos(q(2))*cos(q(4)) - com_lower_leg^2*dq(1)^2*...
         mass_lower_leg*cos(q(2))*cos(q(4))*sin(q(3))*sin(q(2))*sin(q(4)) + 2*com_lower_leg^2*dq(2)*dq(1)*mass_lower_leg*...
         cos(q(3))*cos(q(4))*sin(q(2))*sin(q(4)) - com_lower_leg*dq(1)^2*l_upper_leg*mass_lower_leg*cos(q(2))*...
         sin(q(3))*sin(q(2))*sin(q(4)) - 2*com_lower_leg*dq(1)*dq(4)*l_upper_leg*mass_lower_leg*cos(q(3))*cos(q(2))*cos(q(4));
  W(4,1)=com_lower_leg*mass_lower_leg*(com_lower_leg*ddq(4) + dq(3)^2*l_upper_leg*sin(q(4)) +...
          dq(1)^2*l_upper_leg*sin(q(4)) + g*cos(q(4))*sin(q(2)) + (com_lower_leg*dq(3)^2*sin(2*q(4)))/2 -...
          (com_lower_leg*dq(2)^2*sin(2*q(4)))/2 + (com_lower_leg*dq(1)^2*sin(2*q(4)))/2 - com_lower_leg*ddq(2)*cos(q(3)) - g*...
         cos(q(3))*cos(q(2))*sin(q(4)) + dq(2)^2*l_upper_leg*cos(q(3))^2*sin(q(4)) - ddq(2)*l_upper_leg*cos(q(3))*...
         cos(q(4)) + com_lower_leg*ddq(1)*cos(q(2))*sin(q(3)) - com_lower_leg*dq(1)^2*cos(q(3))*cos(q(2))*sin(q(2)) + 2*...
         dq(3)*dq(2)*l_upper_leg*cos(q(4))*sin(q(3)) - 2*com_lower_leg*dq(2)*dq(1)*sin(q(3))*sin(q(2)) + 2*dq(3)*...
         dq(1)*l_upper_leg*sin(q(2))*sin(q(4)) + com_lower_leg*dq(2)^2*cos(q(3))^2*cos(q(4))*sin(q(4)) -...
          com_lower_leg*dq(1)^2*cos(q(2))^2*cos(q(4))*sin(q(4)) + 2*com_lower_leg*dq(3)*dq(2)*cos(q(4))^2*sin(q(3)) +...
          ddq(1)*l_upper_leg*cos(q(2))*cos(q(4))*sin(q(3)) - dq(1)^2*l_upper_leg*cos(q(3))^2*cos(q(2))^2*sin(q(4)) +...
          2*dq(3)*dq(1)*l_upper_leg*cos(q(3))*cos(q(2))*cos(q(4)) + 2*com_lower_leg*dq(3)*dq(1)*cos(q(4))*...
         sin(q(2))*sin(q(4)) + 2*com_lower_leg*dq(1)^2*cos(q(3))*cos(q(2))*cos(q(4))^2*sin(q(2)) + 2*com_lower_leg*...
         dq(3)*dq(1)*cos(q(3))*cos(q(2))*cos(q(4))^2 + 2*com_lower_leg*dq(2)*dq(1)*cos(q(4))^2*sin(q(3))*...
         sin(q(2)) - com_lower_leg*dq(1)^2*cos(q(3))^2*cos(q(2))^2*cos(q(4))*sin(q(4)) + dq(1)^2*l_upper_leg*cos(q(3))*...
         cos(q(2))*cos(q(4))*sin(q(2)) - 2*dq(2)*dq(1)*l_upper_leg*cos(q(3))*cos(q(2))*sin(q(3))*sin(q(4)) - 2*...
         com_lower_leg*dq(2)*dq(1)*cos(q(3))*cos(q(2))*cos(q(4))*sin(q(3))*sin(q(4)));

 